version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-php-node:22.04
    container_name: laravel-container
    restart: always
    tty: true
    ports:
      - "7000:5000"
    environment:
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/var/www/laravel
      - .Documents/Projetos/favoo-app/docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
      - redis
    networks:
      - laravel_app

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel_app

  redis:
    image: redis:alpine
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - laravel_app

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog-container
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel_app

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/laravel
      - ./Projetos/favoo-app/docker/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_app

networks:
  laravel_app:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
