services:

  laravel:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: laravel-php-node:22.04
    container_name: laravel-container
    restart: always
    tty: true
    environment:
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/var/www/laravel
    depends_on:
      - mysql
      - redis
    networks:
      - laravel_app
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.laravel.rule=PathPrefix(`/`)"
    - "traefik.http.services.laravel.loadbalancer.server.port=5000"
    - "traefik.http.routers.laravel.entrypoints=web"

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel_app

  redis:
    image: redis:alpine
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - laravel_app

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog-container
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel_app

  traefik:
    image: traefik:latest
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=laravel_app
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.email=ricardov7070@gmail.com
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --api.insecure=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Apenas para painel
    volumes:
      - ./traefik/certificates:/letsencrypt
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - laravel_app

networks:
  laravel_app:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
