version: '3.8'

services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-php-node:22.04
        container_name: laravel-container
        ports:
            - '7000:5000'
        environment:
            APP_ENV: '${APP_ENV}'
            APP_KEY: '${APP_KEY}'
            APP_DEBUG: '${APP_DEBUG}'
            APP_URL: '${APP_URL}'
            DB_HOST: '${DB_HOST}'
            DB_PORT: '${DB_PORT}'
            DB_DATABASE: '${DB_DATABASE}'
            DB_USERNAME: '${DB_USERNAME}'
            DB_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - .:/var/www/laravel
        depends_on:
            - mysql
            - redis
        networks:
            - sail

    mysql:
        image: 'mysql:8.0'
        container_name: mysql-container
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - sail

    redis:
        image: 'redis:alpine'
        container_name: redis-container
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data
        networks:
            - sail

    mailhog:
        image: 'mailhog/mailhog:latest'
        container_name: mailhog-container
        ports:
            - '1025:1025'
            - '8025:8025'
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    mysql-data:
        driver: local
    redis-data:
        driver: local
